# Generated by Django 4.2.7 on 2025-09-30 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_analyses', models.PositiveIntegerField(default=0)),
                ('unique_sessions', models.PositiveIntegerField(default=0)),
                ('average_confidence', models.FloatField(default=0.0)),
                ('average_processing_time', models.FloatField(default=0.0)),
                ('feedback_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('neutral_count', models.PositiveIntegerField(default=0)),
                ('depression_count', models.PositiveIntegerField(default=0)),
                ('anxiety_count', models.PositiveIntegerField(default=0)),
                ('stress_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TextAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(help_text='Anonymous session tracking', max_length=100)),
                ('text_input', models.TextField(help_text='Original text submitted for analysis')),
                ('text_length', models.PositiveIntegerField()),
                ('prediction', models.CharField(choices=[('neutral', 'Neutral'), ('depression', 'Depression'), ('anxiety', 'Anxiety'), ('stress', 'Stress')], max_length=20)),
                ('confidence_score', models.FloatField(help_text='Model confidence (0-1)')),
                ('probabilities', models.JSONField(help_text='All class probabilities')),
                ('model_used', models.CharField(choices=[('baseline', 'Baseline Model'), ('advanced', 'Advanced Model'), ('ensemble', 'Ensemble Model')], default='baseline', max_length=20)),
                ('model_version', models.CharField(default='1.0', max_length=10)),
                ('processing_time', models.FloatField(help_text='Time taken to process (seconds)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '⭐ Poor'), (2, '⭐⭐ Fair'), (3, '⭐⭐⭐ Good'), (4, '⭐⭐⭐⭐ Very Good'), (5, '⭐⭐⭐⭐⭐ Excellent')])),
                ('feedback_text', models.TextField(blank=True, help_text='Optional written feedback')),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.textanalysis')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='textanalysis',
            index=models.Index(fields=['prediction', 'created_at'], name='core_textan_predict_0ba089_idx'),
        ),
        migrations.AddIndex(
            model_name='textanalysis',
            index=models.Index(fields=['model_used', 'created_at'], name='core_textan_model_u_aea294_idx'),
        ),
        migrations.AddIndex(
            model_name='textanalysis',
            index=models.Index(fields=['session_id'], name='core_textan_session_99b0d0_idx'),
        ),
    ]
