# Generated by Django 5.2.7 on 2026-01-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_textanalysis_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedback',
            name='correct_label',
            field=models.CharField(blank=True, help_text='User suggested correct label if prediction was wrong', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='textanalysis',
            name='model_used',
            field=models.CharField(choices=[('baseline', 'Baseline Model'), ('advanced', 'Advanced Model'), ('embedded', 'Embedded BERT'), ('ensemble', 'Ensemble Model')], default='baseline', max_length=20),
        ),
    ]
